### PR TITLE
Abstract away database interface with sqlalchemy

### PR DESCRIPTION
**Pull request by kelvinabrokwa**
This PR moves incorporates sqlalchemy as our database library of choice. Its advantages include:
- more easily switch databases later if need be since the interface with the database is abstracted
- easier database set up; creating tables based on data type definition is handled automatically by sqlalchemy
- much easier interactions with the database

This PR also:
- changes the module name from `tribesat` to `tribesat_backend`
- adds a `.pylintrc` for disabling linting rules we don't care about

### CODE REVIEW

**Comment by kelvinabrokwa** [comment]
@Weech4theStars in light of this PR, your database population tool `populate_db.py` may become as simple as something along then lines of:

```py
from random import randint
from tribesat_backend.db import session, Temperature

for i in range(NUMBER_OF_ROWS_TO_ADD):
    session.add(Temperature(temperature=randint(MIN_TEMP, MAX_TEMP)))

session.commit()
```

Note that this will also take care of the creating tables in the DB step!

**Review by eriknstevenson — DISMISSED** [review]
Cool!

**Comment by kelvinabrokwa** [comment]
@narrative thanks for the review but still a `WIP ==  work in progress` (see `WIP` label). Will ping again for review when its ready.

Definitely gonna get the tests passing first.

**Review by Weech4theStars — APPROVED** [review]
looks dank

**Pull request merged**
