### PR TITLE
DB setup scripts

### PR DESCRIPTION
**Pull request by kelvinabrokwa**
re: https://github.com/tribesat/backend/issues/3

creates a `tribesat` database and a single table `temperature` (supposedly for numerical temperature data)

these scripts will be extended in the future as we figure out
1) what we are recording
2) table schemas

### CODE REVIEW

**Comment by eriknstevenson** [comment]
This looks good, if not a bit low-level. Would it be worth it to consider using [SQLAlchemy](https://www.sqlalchemy.org/)?

**Comment by kelvinabrokwa** [comment]
@narrative thats a good suggestion. If we're going to go the ORM route on this project I feel like that'll be an all or nothing kind of deal (that is, we're married to SQLAlchemy or we don't use it at all).

How do you feel about taking that path? I know people coming from Rails will probably into that kind of thing.

**Comment by eriknstevenson** [comment]
Admittedly, I'm quite new to python and haven't used either psycopg2 or SQLAlchemy. That being said, I think the ORM might be nice as it looks quite simple to pick up and may be a time saver. I might have some time this weekend to take a shot at getting basic stuff going with it.

**Comment by Weech4theStars** [comment]
looks good to me. Even though this isn't officially merged yet, I'll make sure the database population script I'm working on writes to the database set up by this script. As for the SQLAlchemy debate, I haven't used it but if it will simplify things down the road, I'm for it

**Comment by kelvinabrokwa** [comment]
I'm going to go ahead and merge this.

@Weech4theStars @narrative just FYI, to review a PR, click on the `Files changed` tab and then click the `Review changes` at the top right to start an official review. Thanks 😄

(I can merge this without official review because I'm an admin but you won't be able to without an official review)

**Comment by kelvinabrokwa** [comment]
@narrative @Weech4theStars re: SQLAlchemy I've come to the conclusion that its the right thing to do. Moving towards that is happening in https://github.com/tribesat/backend/pull/9

**Pull request merged**
